### ISSUE TITLE
Lapis supercompact item model missing

### ISSUE THREAD

**Issue by juh9870** [SupremeMarshal/PlanetCore#16]
![image](https://user-images.githubusercontent.com/15922601/150986292-aefea76c-0123-4457-a361-664242227a46.png)

**Comment by SupremeMarshal** [comment]
This is wierd, I checked lapis json files and everything is fine and I see the item correctly in game. I'm going to try investigating further but no promise on that one.

**Comment by SupremeMarshal** [comment]
Can I see your log when you start the game?

**Comment by juh9870** [comment]
Sure, will send longs once I'm back to PC next morning

**Comment by juh9870** [comment]
[2022-01-25-1.log](https://github.com/SupremeMarshal/PlanetCore/files/7944724/2022-01-25-1.log)

**Comment by SupremeMarshal** [comment]
There is nothing  about lapis supercompact in this log. I also see that you have a problem with geckoLib. Also caves should no longer crash your game with latest planetcore version. Can you download latest geckolib for 1.12.2 and latest planetcore and see if things are working fine?

**Comment by juh9870** [comment]
Hmm, can't reproduce this now neither on the old version nor the new one.
